### PR TITLE
Fix bug in kill disconnect sessions

### LINKED ISSUE #174: bug in kill disconnect sessions
Killing disconnected sessions should not happen when `KillDisconnected=false` but it actually happens.

## sesman.ini:
```
KillDisconnected=false
DisconnectedTimeLimit=120
```

## Environment variables of xorgxrdp:
```
XRDP_START_HEIGHT=1440
XRDP_START_WIDTH=2560
XRDP_SESMAN_KILL_DISCONNECTED=0 <-- HERE: this is 0
XRDP_SESMAN_MAX_DISC_TIME=120 <-- HERE
XRDP_SESMAN_MAX_IDLE_TIME=0
PULSE_SCRIPT=/usr/local/etc/xrdp/pulse/default.pa
XRDP_PULSE_SOURCE_SOCKET=xrdp_chansrv_audio_in_socket_10
XRDP_PULSE_SINK_SOCKET=xrdp_chansrv_audio_out_socket_10
XRDP_SOCKET_PATH=/tmp/.xrdp
XRDP_SESSION=1
DISPLAY=:10.0 HOME=/home/meta
UID=1001
LOGNAME=meta
USER=meta
PATH=/sbin:/bin:/usr/bin:/usr/local/bin
SHELL=/usr/local/bin/zsh
```

## Xorg.10.log:
```
(snip)
[2613456.083] (==) XRDPDEV(0): Backing store enabled
[2613456.084] rdpClientConInit: disconnect idle session after [0] sec
[2613456.084] rdpClientConInit: kill disconnected [1] timeout [120] sec <-- HERE: set to 1
[2613456.084] rdpXvInit: depth 24
[2613456.084] rdpScreenInit: out
[2613456.084] (II) Initializing extension Generic Event Extension
[2613456.084] (II) Initializing extension SHAPE
[2613456.085] (II) Initializing extension MIT-SHM
(snip)
[2615245.648] rdpClientConRecv: g_sck_recv failed(returned 0)
[2615245.648] rdpClientConRecvMsg: error
[2615245.648] rdpClientConCheck: rdpClientConGotData failed
[2615245.648] rdpClientConDisconnect:
[2615245.648] rdpClientConDisconnect: engaging disconnect timer, exit after 120 seconds <-- and HERE
[2615245.648] rdpRemoveClientConFromDev: removing clientCon 0x809e5fc40
```

### PR DESCRIPTION
**Pull request by metalefty**
Killing disconnected sessions should not happen if
XRDP_SESMAN_KILL_DISCONNECTED=0.

Fixes #174.

Signed-off-by: Koichiro IWAO <meta@vmeta.jp>

### CODE REVIEW

File: module/rdpClientCon.c [hunk 1]
```diff
@@ -1401,15 +1401,18 @@ rdpClientConInit(rdpPtr dev)
...
     }
     ptext = getenv("XRDP_SESMAN_KILL_DISCONNECTED");
     if (ptext != 0)
     {
         i = atoi(ptext);
-        if (i != 0)
+        if (i == 0)
+        {
+            dev->do_kill_disconnected = 0;
+        }
```
Comment (metalefty) [inline module/rdpClientCon.c:1414]: This is a little bit redundant but just to be sure.

**Review by matt335672 — COMMENTED** [review]
This all looks OK. but you might want to also change the wording in `xrdp/docs/man.sesman.ini.5.in`:-

```
       DisconnectedTimeLimit=number
              . . .
             You do not actually have to specify KillDisconnected if you set this value.
```
I think this is now wrong. Personally I think it's better the way you've now set it up.

**Review by matt335672 — APPROVED** [review]

**Comment by metalefty** [comment]
Good catch. You did make the change for the man page to match actual behavior.
I think we should fix the behavior rather than the document. Thanks for the feedback!
